// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID             int32            `json:"id"`
	ParentID       pgtype.Int4      `json:"parent_id"`
	UserID         string           `json:"user_id"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	Completed      bool             `json:"completed"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompleteBefore pgtype.Timestamp `json:"complete_before"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

type User struct {
	ID           string           `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	IsAdmin      bool             `json:"is_admin"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
