// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, list_id, user_id, parent_id, title, description, complete_before)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at
`

type CreateTodoParams struct {
	ID             string           `json:"id"`
	ListID         string           `json:"list_id"`
	UserID         string           `json:"user_id"`
	ParentID       pgtype.Text      `json:"parent_id"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	CompleteBefore pgtype.Timestamp `json:"complete_before"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.ID,
		arg.ListID,
		arg.UserID,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.CompleteBefore,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ListID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompleteBefore,
		&i.CompletedAt,
	)
	return i, err
}
