// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, username, is_admin, created_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

type CreateUserRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	IsAdmin   bool             `json:"is_admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, is_admin, created_at
FROM users
`

type GetAllUsersRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	IsAdmin   bool             `json:"is_admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordHashByUsername = `-- name: GetPasswordHashByUsername :one
SELECT password_hash
FROM users
WHERE username = $1
`

func (q *Queries) GetPasswordHashByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHashByUsername, username)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, is_admin, created_at
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	IsAdmin   bool             `json:"is_admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id string) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, password_hash = $3, is_admin = $4
WHERE id = $1
RETURNING id, username, is_admin, created_at
`

type UpdateUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

type UpdateUserRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	IsAdmin   bool             `json:"is_admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
